/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.0/userguide/building_java_projects.html
 */

val logback_version: String by project
val ktor_version: String by project
val kotlin_version: String by project

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    
    kotlin("jvm") version "1.4.32"
    kotlin("plugin.serialization") version "1.4.32"

    id("com.github.johnrengelman.shadow") version "7.0.0"
}

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    implementation(platform("org.jetbrains.kotlin:kotlin-bom")) // Align versions of all Kotlin components
    implementation("io.ktor:ktor-server-core:$ktor_version")
    implementation("io.ktor:ktor-server-netty:$ktor_version")
    implementation("ch.qos.logback:logback-classic:$logback_version")
    implementation("io.ktor:ktor-serialization:$ktor_version")
    implementation("com.apurebase:kgraphql:0.17.5")
    implementation("com.apurebase:kgraphql-ktor:0.17.5")

    testImplementation("org.jetbrains.kotlin:kotlin-test") // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit") // Use the Kotlin JUnit integration.
    testImplementation("io.ktor:ktor-server-tests:$ktor_version")
}

application {
    // Define the main class for the application.
    mainClass.set("com.xapphire13.wfs.AppKt")
}

tasks {
    compileKotlin { kotlinOptions { jvmTarget = "1.8" } }
    compileTestKotlin { kotlinOptions { jvmTarget = "1.8" } }
}

sourceSets["main"].resources.srcDirs("resources")